baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Blog'
theme = 'ayn'
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
footnotereturnlinkcontents = "↩"

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "About"
url = "about/"
weight = 5

[[menu.main]]
name = "Subscribe"
url = "index.xml"
weight = 4

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
inline = [ [ "\\(", "\\)" ] ]

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 3
